exports.decorateConfig = (config) =>
  Object.assign({}, config, {
    fontSize: 14,
    fontFamily: "IBMPlexMono, 'Roboto Mono', monospace",
    cursorColor: "#59ff1a",
    cursorShape: "UNDERLINE",
    cursorBlink: true,
    borderColor: "#202121",
    padding: "7px",
    colors: {
      black: "#202121",
      red: "#f73e2a",
      green: "#59ff1a",
      yellow: "#f7dd72",
      blue: "#00a8ff",
      magenta: "#f746ff",
      cyan: "#1effff",
      white: "#fff",
      lightBlack: "#202121",
      lightRed: "#f73e2a",
      lightGreen: "#59ff1a",
      lightYellow: "#f7dd72",
      lightBlue: "#00a8ff",
      lightMagenta: "#f746ff",
      lightCyan: "#1effff",
      lightWhite: "#fff",
    },
    bell: false,
    keymaps: {
      "tab:new": "ctrl+t",
      "window:new": "ctrl+shift+n",
      "editor:undo": "ctrl+z",
      "editor:redo": "ctrl+y",
      "editor:copy": "ctrl+c",
      "editor:paste": "ctrl+v",
      "editor:selectAll": "ctrl+a",
      "editor:break": "ctrl+d",
    },
  });
